//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Teams.Apps.Athena.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Teams.Apps.Athena.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AdaptiveCardDateLabel {
            get {
                return ResourceManager.GetString("AdaptiveCardDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string AdaptiveCardStatusLabel {
            get {
                return ResourceManager.GetString("AdaptiveCardStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string AdaptiveCardTitleLabel {
            get {
                return ResourceManager.GetString("AdaptiveCardTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string AdaptiveCardTypeLabel {
            get {
                return ResourceManager.GetString("AdaptiveCardTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View details.
        /// </summary>
        public static string AdaptiveCardViewDetailsButtonLabel {
            get {
                return ResourceManager.GetString("AdaptiveCardViewDetailsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community of interest request.
        /// </summary>
        public static string CoiRequestAdaptiveCardTitle {
            get {
                return ResourceManager.GetString("CoiRequestAdaptiveCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COI.
        /// </summary>
        public static string CoiText {
            get {
                return ResourceManager.GetString("CoiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string CoiTypePrivate {
            get {
                return ResourceManager.GetString("CoiTypePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string CoiTypePublic {
            get {
                return ResourceManager.GetString("CoiTypePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string EventText {
            get {
                return ResourceManager.GetString("EventText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        public static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tenant..
        /// </summary>
        public static string InvalidTenantText {
            get {
                return ResourceManager.GetString("InvalidTenantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News article request.
        /// </summary>
        public static string NewsRequestAdaptiveCardTitle {
            get {
                return ResourceManager.GetString("NewsRequestAdaptiveCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsText {
            get {
                return ResourceManager.GetString("NewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string PartnerText {
            get {
                return ResourceManager.GetString("PartnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string RequestStatusApproved {
            get {
                return ResourceManager.GetString("RequestStatusApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string RequestStatusDraft {
            get {
                return ResourceManager.GetString("RequestStatusDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string RequestStatusPending {
            get {
                return ResourceManager.GetString("RequestStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string RequestStatusRejected {
            get {
                return ResourceManager.GetString("RequestStatusRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Paper.
        /// </summary>
        public static string ResearchPaperText {
            get {
                return ResourceManager.GetString("ResearchPaperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Project.
        /// </summary>
        public static string ResearchProjectText {
            get {
                return ResourceManager.GetString("ResearchProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Proposal.
        /// </summary>
        public static string ResearchProposalText {
            get {
                return ResourceManager.GetString("ResearchProposalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Request.
        /// </summary>
        public static string ResearchRequestText {
            get {
                return ResourceManager.GetString("ResearchRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsButtonText {
            get {
                return ResourceManager.GetString("SettingsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor.
        /// </summary>
        public static string SponsorText {
            get {
                return ResourceManager.GetString("SponsorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string TaskModuleErrorTitle {
            get {
                return ResourceManager.GetString("TaskModuleErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserText {
            get {
                return ResourceManager.GetString("UserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COI request details.
        /// </summary>
        public static string ViewCoiDetailsTaskModuleTitle {
            get {
                return ResourceManager.GetString("ViewCoiDetailsTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News article request details.
        /// </summary>
        public static string ViewNewsArticleDetailsTaskModuleTitle {
            get {
                return ResourceManager.GetString("ViewNewsArticleDetailsTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some of the things I can do:-.
        /// </summary>
        public static string WelcomeCardContentLine1 {
            get {
                return ResourceManager.GetString("WelcomeCardContentLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to get started? Configure my settings!.
        /// </summary>
        public static string WelcomeCardContentLine2 {
            get {
                return ResourceManager.GetString("WelcomeCardContentLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help you view all notification of requests you have raised for COI and news.
        /// </summary>
        public static string WelcomeCardContentPoint1 {
            get {
                return ResourceManager.GetString("WelcomeCardContentPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert you when your FAQ question gets answered.
        /// </summary>
        public static string WelcomeCardContentPoint2 {
            get {
                return ResourceManager.GetString("WelcomeCardContentPoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide regular update of news.
        /// </summary>
        public static string WelcomeCardContentPoint3 {
            get {
                return ResourceManager.GetString("WelcomeCardContentPoint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi there, I’m the Athena bot.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
    }
}
